FROM continuumio/miniconda3

RUN conda install conda-forge::polars
RUN conda install conda-forge::goatools
RUN conda install bioconda::cafe
RUN conda install conda-forge::biopython
RUN conda install bioconda::mafft
RUN conda install bioconda::iqtree
RUN conda install conda-forge::openmpi=4.1.4=ha1ae619_100
RUN conda install bioconda::generax
RUN conda install bioconda::pal2nal
RUN conda install bioconda::trimal
RUN conda install conda-forge::ete3
RUN conda install bioconda::sra-tools
RUN conda install bioconda::fastp
RUN conda install bioconda::bwa-mem2
RUN conda install bioconda::samtools
RUN conda install conda-forge::matplotlib
