import polars as pl
import argparse
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# Parse
parser = argparse.ArgumentParser()
parser.add_argument('--output')
args = parser.parse_args()

record_list = []
seq = Seq('MEAFNFQVILLVGLCVSSSFADYKDDDDKFPPTRYTQDASFQSLANTSRSEIVQQQQQQKSKAEEPQQVNTIRVTCHPDSLEIVIKADMFAVGAPVDADEIRLGVETNNQYCRATASSADEYSISVGLVECGTRHWVTEDSLIYTNLLIYSPEASPYGVVRMDEAVIPIECHYERKYSVSSSSLMPTWIPFMSTQAAVEMLQFNLRIMTSDWQYKRSSNVFHLGEPISIEASVRIGHHMGLRVFVSSCVATLSPDMNSSPRHAFIENGCFVDSQLPGSRSQFLARTQDDKLHMSIDAFRFYNEDRGELYITCHLNAEPINDADATNKACTFVNGRWRSADGNDYLCGQCKRSIEVEQTPSKPSSPSKFRPRGFVKPEEREPLWRSGLKTSTVWEHQARVGPLMVLPAKQKSRPIPAKQRSSILDQISRSTMYGSQWRSGINRVDQRKGLLPDSSSTQNQVAVLTLASEQNQDGEDKSGTEKDEDAEEVHELLEKTSPEAHLQSKAAVLNGTDTAALDEVFPTAAVNVAVPPLSNTTATVSDLSETMDPKRK')
record_list.append(SeqRecord(seq, id='Dissostichus_mawsoni_DmZPC5', description='Cao et al. 2016. Nat. Commun., Supplementary Figure 5, DmZPC5'))
SeqIO.write(record_list, args.output, 'fasta')